name: Push dist directory to dist branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0' # Or whatever version of Node.js your project requires

    - name: Cache Node.js modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # Cache dependencies using a hash of the package-lock.json file as the key
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        npm install
        npm install --global gulp-cli

    - name: Run gulp build
      run: gulp # This command assumes that your gulp tasks are defined in gulpfile.js

    - name: Push dist directory to dist branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
        publish_branch: dist
        keep_files: true  # Set to true to keep existing files in the branch